name: Branch Specific Workflow

on:
  workflow_call:
    inputs:
      greeting:
        description: 'The greeting to use'
        type: string
        required: true
        default: 'Hello'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "${{ inputs.greeting }} World!"
