name: Calling Workflow

on:
  workflow_dispatch:
  # Works with schedules as well, but commented out to not continously consume my action minutes ;)
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  call_branch_specific_workflow:
    name: Call Branch Specific Workflow
    uses: davelosert/action-test-repository/.github/workflows/branched-workflow.yml@workflow-branch
    with:
      greeting: Hello
