name: Calling Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call_branch_specific_workflow:
    name: Call Branch Specific Workflow
    uses: davelosert/action-test-repository/.github/workflows/branched-workflow.yml@workflow-branch
    with:
      greeting: Hello
