name: Report Coverage

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null, 2)

      - uses: davelosert/vitest-coverage-report-action@v2
        name: "Report Coverage"
