name: Test Dependency Review PR Comment Addition

on: 
  pull_request:
    branches: [main]
    
permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review PR Comment Addition
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: davelosert/dependency-review-action@adjust_summary_format
        with:
          comment-summary-in-pr: true
